-- PixelStore PostgreSQL schema (all 23 tables).
--
-- Design notes (see docs/POSTGRES-MIGRATION-RUNBOOK.md for the full rationale):
--   * Table and column names are identical to the SQLite schema so the exact
--     same route queries run against both engines.
--   * IDs are GENERATED BY DEFAULT AS IDENTITY: normal inserts get automatic
--     ids, while the one-way migration can still import explicit SQLite ids.
--     The migration script repairs every sequence afterwards.
--   * Timestamps are TIMESTAMPTZ (SQLite stored UTC 'YYYY-MM-DD HH:MM:SS' text;
--     values migrate with SET TIME ZONE 'UTC' so instants are preserved).
--   * Boolean flags stay INTEGER 0/1 on purpose: converting to BOOLEAN would
--     require rewriting ~100 query predicates and every row-mapping the app
--     relies on (e.g. `read = 0`, `is_active = 1`). Same values, zero risk.
--   * No extensions required. Case-insensitive coupon uniqueness uses a
--     UNIQUE index on lower(code) instead of CITEXT, so this file runs on any
--     stock PostgreSQL (including hardened managed instances).
--   * This file is idempotent (IF NOT EXISTS throughout) and creates NO demo
--     data. Seeding demo data requires SEED_DEMO_DATA=true explicitly.
--   * Never run against SQLite. Applied by scripts/init-postgres-schema.js
--     and automatically (harmlessly) at application boot in postgres mode.

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT UNIQUE NOT NULL,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name     TEXT DEFAULT '',
  phone         TEXT DEFAULT '',
  address       TEXT DEFAULT '',
  avatar        TEXT DEFAULT 'img/bg-img/9.jpg',
  balance       DOUBLE PRECISION DEFAULT 0,
  role          TEXT DEFAULT 'customer',
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  slug        TEXT NOT NULL UNIQUE,
  description TEXT DEFAULT '',
  image       TEXT DEFAULT '',
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT UNIQUE NOT NULL,
  name        TEXT NOT NULL,
  description TEXT DEFAULT '',
  price       DOUBLE PRECISION NOT NULL,
  old_price   DOUBLE PRECISION,
  image       TEXT NOT NULL,
  category    TEXT DEFAULT 'GoPro Accessories',
  badge       TEXT,
  stock       INTEGER DEFAULT 100,
  rating      DOUBLE PRECISION DEFAULT 0,
  rating_count INTEGER DEFAULT 0,
  featured    INTEGER DEFAULT 0,
  flash_sale  INTEGER DEFAULT 0,
  reorder_threshold INTEGER DEFAULT 10,
  category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  sku         TEXT,
  status      TEXT NOT NULL DEFAULT 'active',
  brand       TEXT DEFAULT '',
  mpn         TEXT DEFAULT '',
  gtin        TEXT DEFAULT '',
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_images (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  image_data  TEXT NOT NULL,
  mime_type   TEXT NOT NULL,
  file_name   TEXT DEFAULT '',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_primary  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS carts (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id) ON DELETE CASCADE,
  guest_id   TEXT,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity   INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wishlists (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id) ON DELETE CASCADE,
  guest_id   TEXT,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER REFERENCES users(id) ON DELETE CASCADE,
  guest_id    TEXT,
  full_name   TEXT NOT NULL,
  email       TEXT NOT NULL,
  phone       TEXT NOT NULL,
  address     TEXT NOT NULL,
  shipping_method TEXT DEFAULT 'standard',
  payment_method  TEXT DEFAULT 'cash',
  subtotal    DOUBLE PRECISION NOT NULL,
  shipping_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
  discount_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  coupon_code TEXT DEFAULT '',
  total       DOUBLE PRECISION NOT NULL,
  status      TEXT DEFAULT 'pending',
  carrier     TEXT DEFAULT '',
  tracking_number TEXT DEFAULT '',
  shipping_status TEXT DEFAULT 'pending',
  shipping_notes TEXT DEFAULT '',
  internal_notes TEXT DEFAULT '',
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS coupons (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                TEXT NOT NULL,
  discount_type       TEXT NOT NULL CHECK(discount_type IN ('percentage', 'fixed')),
  discount_value      DOUBLE PRECISION NOT NULL CHECK(discount_value > 0),
  minimum_order_amount DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(minimum_order_amount >= 0),
  maximum_discount    DOUBLE PRECISION CHECK(maximum_discount IS NULL OR maximum_discount >= 0),
  usage_limit         INTEGER CHECK(usage_limit IS NULL OR usage_limit >= 0),
  usage_count         INTEGER NOT NULL DEFAULT 0 CHECK(usage_count >= 0),
  expires_at          TIMESTAMPTZ,
  is_active           INTEGER NOT NULL DEFAULT 1,
  created_at          TIMESTAMPTZ DEFAULT now(),
  updated_at          TIMESTAMPTZ DEFAULT now()
);
-- Case-insensitive uniqueness without any extension.
CREATE UNIQUE INDEX IF NOT EXISTS idx_coupons_code_lower_unique ON coupons (lower(code));

CREATE TABLE IF NOT EXISTS promotional_banners (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image         TEXT NOT NULL,
  title         TEXT NOT NULL,
  description   TEXT DEFAULT '',
  button_text   TEXT DEFAULT '',
  button_url    TEXT DEFAULT '',
  is_active     INTEGER NOT NULL DEFAULT 1,
  display_order INTEGER NOT NULL DEFAULT 0,
  starts_at     TIMESTAMPTZ,
  ends_at       TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payments (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        INTEGER NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
  payment_method  TEXT NOT NULL,
  payment_status  TEXT NOT NULL DEFAULT 'pending' CHECK(payment_status IN ('pending', 'paid', 'failed', 'refunded')),
  transaction_id  TEXT DEFAULT '',
  paid_at         TIMESTAMPTZ,
  amount_paid     DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(amount_paid >= 0),
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_status_history (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status      TEXT NOT NULL,
  note        TEXT DEFAULT '',
  changed_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  change      INTEGER NOT NULL,
  reason      TEXT NOT NULL,
  note        TEXT DEFAULT '',
  changed_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id   TEXT NOT NULL,
  details     TEXT DEFAULT '',
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS store_settings (
  id                       INTEGER PRIMARY KEY CHECK(id = 1),
  store_name               TEXT NOT NULL DEFAULT 'PixelHouse',
  contact                  TEXT NOT NULL DEFAULT '{}',
  currency                 TEXT NOT NULL DEFAULT 'LKR',
  store_status             TEXT NOT NULL DEFAULT 'open',
  payment_methods          TEXT NOT NULL DEFAULT '[]',
  shipping_fee             DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(shipping_fee >= 0),
  delivery_options         TEXT NOT NULL DEFAULT '[]',
  notification_preferences TEXT NOT NULL DEFAULT '{}',
  updated_at               TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  name       TEXT NOT NULL,
  price      DOUBLE PRECISION NOT NULL,
  quantity   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS vendor_applications (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER REFERENCES users(id) ON DELETE SET NULL,
  account_type TEXT NOT NULL,
  store_name   TEXT NOT NULL,
  location     TEXT NOT NULL,
  mobile       TEXT NOT NULL,
  status       TEXT DEFAULT 'pending',
  created_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL,
  subject    TEXT DEFAULT '',
  message    TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title   TEXT NOT NULL,
  body    TEXT DEFAULT '',
  type    TEXT DEFAULT 'info',
  read    INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_notifications (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type        TEXT NOT NULL CHECK(type IN ('order', 'customer', 'vendor', 'contact', 'review')),
  title       TEXT NOT NULL,
  body        TEXT DEFAULT '',
  entity_type TEXT NOT NULL,
  entity_id   TEXT NOT NULL,
  read        INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS password_resets (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email   TEXT NOT NULL,
  code    TEXT NOT NULL,
  used    INTEGER DEFAULT 0,
  attempts INTEGER DEFAULT 0,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reviews (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  rating     INTEGER NOT NULL,
  comment    TEXT DEFAULT '',
  is_visible INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS read_messages (
  contact_message_id INTEGER PRIMARY KEY REFERENCES contact_messages(id) ON DELETE CASCADE
);

-- Application indexes (same coverage as SQLite).
CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_products_sku_unique ON products(sku) WHERE sku IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_product_images_product_order ON product_images(product_id, sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_images_primary ON product_images(product_id) WHERE is_primary = 1;
CREATE INDEX IF NOT EXISTS idx_orders_analytics ON orders(created_at, status);
CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_order_items_order_product ON order_items(order_id, product_id);
CREATE INDEX IF NOT EXISTS idx_coupons_active_expiry ON coupons(is_active, expires_at);
CREATE INDEX IF NOT EXISTS idx_promotional_banners_active_dates ON promotional_banners(is_active, starts_at, ends_at, display_order);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(payment_status, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_notifications_read_created ON admin_notifications(read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_filters ON audit_logs(actor_id, action, entity_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_admin_active ON users(role, is_active);
